/* Administration consumes the current session and cloud service in this document. */
(function(){'use strict';const W=window,$=id=>document.getElementById(id),api=()=>W.__STM_NATIVE_ADMIN;let configOwner=null,configDraft=false,configFingerprint='',draftRevision=0,parseSerial=0,parsing=false,scheduled=false;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const allowed=()=>W.currentUser?.role==='admin'&&W.__STM_NATIVE_PLATFORM?.state.authenticated&&W.__STM_NATIVE_PLATFORM?.state.ready;
 function status(message){$('nativeAdminStatus').textContent=message||'';}
 async function run(fn){const token=W.__STM_NATIVE_PLATFORM.captureOwner();try{if(!allowed())throw Error('Administrator access is required.');const result=await fn();W.__STM_NATIVE_PLATFORM.assertOwner(token);render();return result;}catch(e){try{W.__STM_NATIVE_PLATFORM.assertOwner(token);if(allowed()&&!['STM_SUPERSEDED','STM_STALE_OWNER'].includes(e.code))status(e.message||String(e));}catch(_){}return null;}}
 function clear(){configOwner=null;configDraft=false;configFingerprint='';draftRevision++;parseSerial++;parsing=false;for(const id of ['usersAdminList','feedbackAdminList','auditEntries','adminPromptPreview'])$(id).replaceChildren();for(const id of ['usersAdminStatus','feedbackStatus','llmSpendStatus','auditCount','nativeAdminStatus'])$(id).textContent='';$('adminGuidelineText').value='';$('adminModel').replaceChildren();$('adminMaxTokens').value='';$('adminForceGlobal').checked=false;$('adminPromptSelect').replaceChildren();}
 function panel(kind,data,id,renderer){$(id).innerHTML=data.status==='loading'?'<p>Loading…</p>':data.status==='error'?'<p role="alert">'+esc(data.error)+'</p>':data.status==='ready'?renderer(data):'<p>Open Administration or refresh to load '+kind+'.</p>';}
 function settings(s,force=false){const owner=s.user.id,c=s.config;if(!c)return;const fingerprint=JSON.stringify([c.api,c.custom,c.guideline]);if(!force&&owner===configOwner&&(configDraft||configFingerprint===fingerprint))return;configOwner=owner;configDraft=false;configFingerprint=fingerprint;$('adminModel').innerHTML=c.models.map(m=>'<option value="'+esc(m.value)+'">'+esc(m.label)+'</option>').join('');$('adminModel').value=c.api.model;$('adminMaxTokens').value=c.api.maxTokens;$('adminForceGlobal').checked=!!c.api.forceGlobal;$('adminGuidelineText').value=c.custom?c.guideline:'';}
 function render(){if(!allowed()){clear();return;}const s=api().read();settings(s);
  $('usersAdminStatus').textContent=s.users.status==='ready'?s.users.rows.length+' users · '+new Set(s.users.rows.map(r=>r.role)).size+' roles':s.users.status;
  panel('users',s.users,'usersAdminList',v=>'<div class="admin-user-table"><table><thead><tr><th>Account</th><th>Role</th><th>Submissions</th></tr></thead><tbody>'+v.rows.map(u=>'<tr><td><b>'+esc(u.display_name||u.email||'Name not reported')+'</b><small>'+esc(u.email)+'</small></td><td>'+esc(u.role||'Not reported')+'</td><td>'+u.submission_count+'</td></tr>').join('')+'</tbody></table></div>');
  const f=s.feedback.summary;$('feedbackStatus').textContent=f?f.total+' events · '+f.up+' positive · '+f.down+' negative · '+f.comment+' comments · '+f.unexported+' unexported':s.feedback.status;
  panel('feedback',s.feedback,'feedbackAdminList',v=>v.rows.length?'<p class="admin-scope">Latest '+v.rows.length+' events</p>'+v.rows.map(r=>'<article><b>'+esc(r.module_key)+' · '+esc(r.rating)+'</b><p>'+esc(r.comment||'No comment')+'</p><small>'+esc(r.created_at)+' · '+esc(r.user_id)+'</small></article>').join(''):'<p>No recorded feedback.</p>');
  panel('audit',s.audit,'auditEntries',v=>v.rows.length?v.rows.map(r=>'<article data-audit-id="'+esc(r.id)+'"><time>'+esc(r.created_at)+'</time><div><b>'+esc(r.category)+'</b><p>'+esc(r.message)+'</p><small>'+esc(r.user_id||'Actor not reported')+' · '+esc(r.submission_id||'No submission')+'</small><details><summary>Event details</summary><pre>'+esc(JSON.stringify(r.meta||{},null,2))+'</pre></details></div></article>').join(''):'<p>No events for this category.</p>');
  $('auditCount').textContent=s.audit.rows.length+' loaded'+(s.audit.hasMore?' · more available':'');const sel=$('auditCategorySelect');sel.innerHTML='<option value="all">All categories</option>'+s.audit.categories.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('');sel.value=s.audit.category;
  $('adminLoadOlder').disabled=s.audit.status!=='ready'||!s.audit.hasMore;for(const id of ['adminAuditJson','adminAuditCsv'])$(id).disabled=s.audit.status!=='ready';$('adminSaveConfig').disabled=parsing||api().busy||s.config?.pending;for(const id of ['adminModel','adminMaxTokens','adminForceGlobal','adminGuidelineText','adminDefaultGuideline','adminGuidelineFile'])$(id).disabled=api().busy||s.config?.pending;
  for(const e of document.querySelectorAll('[data-admin-availability]'))e.textContent=s.unsupported[e.dataset.adminAvailability]||'';
  document.querySelector('[data-admin-availability="users"]').textContent=s.unsupported.roles;
  const prompt=$('adminPromptSelect'),selected=prompt.value;if(!prompt.options.length){prompt.innerHTML=s.prompts.map(p=>'<option value="'+esc(p.key)+'">'+esc(p.key)+' · '+p.chars.toLocaleString()+' characters</option>').join('');if(selected)prompt.value=selected;}$('adminPromptPreview').textContent=prompt.value?api().prompt(prompt.value):'No prompts available.';
  $('llmSpendStatus').textContent=s.usage.currentRunCost==null?'No active run cost available':'Current run: $'+s.usage.currentRunCost.toFixed(4);
  document.querySelector('[data-admin-state="guidelines"]').textContent=s.config?.custom?'Personal guideline saved':'Embedded default guideline';document.querySelector('[data-admin-state="prompts"]').textContent=s.prompts.length+' original prompts · read only';document.querySelector('[data-admin-state="integrations"]').textContent='No external integrations connected';document.querySelector('[data-admin-state="thresholds"]').textContent='Read only · original pipeline rules';document.querySelector('[data-admin-state="compliance"]').textContent=s.audit.rows.length+' cloud events loaded';
 }
 function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;try{render();}catch(e){if(allowed())status(e.message);}});}
 $('adminRefreshAll').onclick=()=>run(()=>api().refresh());$('adminAuditRefresh').onclick=()=>run(()=>api().refresh('audit'));$('adminFeedbackRefresh').onclick=()=>run(()=>api().refresh('feedback'));$('adminLoadOlder').onclick=()=>run(()=>api().refresh('audit',{append:true}));$('auditCategorySelect').onchange=e=>run(()=>api().refresh('audit',{category:e.target.value}));
 $('adminAuditJson').onclick=()=>run(()=>api().exportAudit('json'));$('adminAuditCsv').onclick=()=>run(()=>api().exportAudit('csv'));$('adminFeedbackExport').onclick=()=>run(async()=>{status('Preparing feedback export…');const r=await api().exportFeedback();status(r.rows+' events downloaded. Exported status was not changed.');});
 $('adminSaveConfig').onclick=()=>run(async()=>{status('Saving personal settings…');await api().configure({model:$('adminModel').value,maxTokens:Number($('adminMaxTokens').value),forceGlobal:$('adminForceGlobal').checked,guideline:$('adminGuidelineText').value});settings(api().read(),true);status('Personal settings saved to your account.');});
 $('adminDefaultGuideline').onclick=()=>{$('adminGuidelineText').value='';configDraft=true;draftRevision++;status('Default guideline selected. Save personal settings to apply it.');};
 $('adminGuidelineFile').onchange=e=>run(async()=>{const file=e.target.files[0];if(!file)return;const serial=++parseSerial,revision=draftRevision;parsing=true;render();status('Reading guideline…');try{const r=await api().parseGuide(file);if(serial!==parseSerial)return;if(revision!==draftRevision){status('Guideline import finished. Your newer text was kept; select the file again to replace it.');return;}$('adminGuidelineText').value=r.text;configDraft=true;draftRevision++;status(r.warning||'Guideline imported. Review and save personal settings to apply it.');}finally{if(serial===parseSerial){parsing=false;e.target.value='';render();}}});
 for(const id of ['adminModel','adminMaxTokens','adminForceGlobal','adminGuidelineText'])$(id).addEventListener('input',()=>{configDraft=true;draftRevision++;status('Unsaved personal settings.');});$('adminPromptSelect').onchange=schedule;$('adminUsageConsole').onclick=()=>run(()=>W.open('https://console.anthropic.com/settings/usage','_blank','noopener,noreferrer'));
 // Replace the original automatic Admin view hooks; all active controls use the service above.
 W.renderAdminUsersCard=()=>run(()=>api().refresh('users'));W.renderAdminFeedbackCard=()=>run(()=>api().refresh('feedback'));W.renderAdminAuditLog=opts=>run(()=>api().refresh('audit',opts||{}));
 W.addEventListener('stm:admin-change',()=>{try{render();}catch(e){if(allowed())status(e.message);}});W.addEventListener('stm:settings-changed',schedule);W.addEventListener('stm:platform-change',()=>{if(!allowed()){api().retire(false);clear();}schedule();});schedule();
})();
