/* The remaining review chapters use their original controls in this document. */
document.addEventListener('DOMContentLoaded',()=>{
 'use strict';const W=window,$=id=>document.getElementById(id),api=()=>W.__STM_WB_PHASE7,wb=()=>W.__STM_WB;
 let picks=new Set(),pickLayer=null;let renderQueued=false,preview={text:'',name:''},statusTimer;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function owned(){W.stmAssertWorkbenchOwner();if(!wb()?.submissionId||wb().restoreError)throw Error(wb()?.restoreError||'Open a submission first.');return wb().submissionId;}
 function notify(message){const e=$('nativeReviewStatus');e.textContent=message;e.hidden=false;clearTimeout(statusTimer);statusTimer=setTimeout(()=>e.hidden=true,6000);}
 async function attempt(fn){try{owned();const r=await fn();schedule();return r;}catch(e){notify(e.message||String(e));return false;}}
 function action(act,data){return attempt(()=>api().action(owned(),act,data));}
 function snapshot(){return api().read(owned());}
 function textDownload(text,name){owned();const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function showPreview(title,text,name,notice){preview={text,name};$('nativeReviewPreviewTitle').textContent=title;$('nativeReviewPreviewText').textContent=text;$('nativeReviewPreviewNotice').textContent=notice||'';$('nativeReviewPreview').showModal();}
 function formText(rows){return 'FORM SCHEDULE\n'+($('dealName')?.value||'Submission')+'\n\n'+rows.map((r,i)=>(i+1)+'. '+r.num+' — '+r.name+'\n   '+r.category).join('\n\n')+'\n\nThis schedule identifies forms. It does not contain policy wording or official form PDFs.\n';}
 function previewForms(row){return attempt(()=>{const data=snapshot(),rows=row?data.forms.filter(f=>f.key===row.dataset.phase7Key):data.forms.filter(f=>f.on);if(!rows.length)throw Error('Select at least one form to preview.');showPreview('Form schedule',formText(rows),'form-schedule.txt','Review the identifiers and names below; official policy wording is not stored here.');api().record(owned(),'Form schedule previewed',rows.length+' form(s)');});}
 function downloadForm(row){return attempt(()=>{const data=snapshot(),form=data.forms.find(f=>f.key===row.dataset.phase7Key);if(!form)throw Error('This form is no longer available.');textDownload(formText([form]),form.num.replace(/[^a-z0-9_-]/gi,'_')+'-schedule.txt');api().record(owned(),'Form schedule downloaded',form.num);});}
 function renderLibrary(){const s=snapshot(),q=$('nativeFormSearch').value.toLowerCase(),present=new Set(s.forms.map(f=>f.num.trim().toUpperCase()));if(pickLayer!==s.layer.key){picks.clear();pickLayer=s.layer.key;}const available=s.library.filter(f=>!present.has(f.num.trim().toUpperCase()));picks=new Set([...picks].filter(n=>available.some(f=>f.num===n)));const rows=available.filter(f=>!q||(f.num+' '+f.name+' '+f.category).toLowerCase().includes(q));$('nativeFormLibraryStatus').textContent=s.layer.key?s.layer.label+' · '+rows.length+' matching forms · '+picks.size+' selected':'Choose a Lead or Excess Layer Type on Deal Information.';$('nativeFormLibrary').innerHTML=rows.map(f=>'<label><input type="checkbox" value="'+esc(f.num)+'" '+(picks.has(f.num)?'checked':'')+'><span><b>'+esc(f.num)+'</b> — '+esc(f.name)+'<small> · '+esc(f.category)+'</small></span></label>').join('')||'<p>No matching forms are available to add.</p>';$('nativeFormAddSelected').disabled=!picks.size;$('nativeCustomFormAdd').disabled=!s.layer.key;}
 function openForms(){return attempt(()=>{snapshot();picks.clear();pickLayer=null;$('nativeFormSearch').value='';$('nativeFormError').textContent='';renderLibrary();$('nativeFormsDialog').showModal();});}
 async function addForms(custom){try{owned();const data=custom?{num:$('nativeCustomFormNumber').value,name:$('nativeCustomFormName').value}:{nums:[...picks]};await api().action(owned(),custom?'forms:custom':'forms:add',data);$('nativeFormError').textContent='';if(custom){$('nativeCustomFormNumber').value='';$('nativeCustomFormName').value='';}else picks.clear();renderLibrary();schedule();notify('Forms added to the schedule. Save to keep these changes.');}catch(e){$('nativeFormError').textContent=e.message;}}
 function addCustomDraft(){return attempt(()=>{const panel=document.querySelector('#form-subjectivities .other-details-panel');if(panel.querySelectorAll('.other-input-group').length>=500)throw Error('At most 500 custom conditions are supported.');const empty=[...panel.querySelectorAll('textarea')].find(e=>!e.value.trim());if(empty){empty.focus();return;}const group=document.createElement('div');group.className='other-input-group';const text=document.createElement('textarea');text.rows=2;text.maxLength=20000;text.placeholder='Enter your condition';text.dataset.phase7On='1';group.append(text);panel.insertBefore(group,panel.querySelector('.add-other-btn'));decorateCustom();text.focus();});}
 function decorateCustom(){for(const wrap of document.querySelectorAll('#form-subjectivities .other-input-group')){const text=wrap.querySelector('textarea');if(!text)continue;text.disabled=false;text.maxLength=20000;text.dataset.phase7Key||='p6-'+crypto.randomUUID();text.dataset.phase7On??='1';if(!wrap.querySelector('.native-custom-toggle')){const label=document.createElement('label');label.className='native-subjectivity-item-label';const cb=document.createElement('input');cb.type='checkbox';cb.className='native-custom-toggle';label.append(cb,document.createTextNode(' Apply this condition'));const remove=document.createElement('button');remove.type='button';remove.dataset.removeCustom='1';remove.textContent='Remove';wrap.append(label,remove);}wrap.querySelector('.native-custom-toggle').checked=text.dataset.phase7On==='1';}}
 function subjectPreview(){return attempt(()=>{const s=snapshot(),items=[...s.subjects,...s.custom].filter(x=>x.on);if(!items.length)throw Error('Apply at least one condition to preview quote text.');const text='SUBJECTIVITIES AND CONDITIONS\n'+($('dealName')?.value||'Submission')+'\n\n'+items.map((x,i)=>(i+1)+'. '+x.text).join('\n\n')+'\n';showPreview('Subjectivities & conditions',text,'subjectivities.txt','Selected wording from this submission. Review before including it in a quote.');});}
 function renderHistory(events){const log=$('historyLog');if(!log)return;const groups=new Map();for(const ev of events||[]){const at=new Date(ev.at),day=Number.isNaN(at.getTime())?'Date not reported':at.toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});if(!groups.has(day))groups.set(day,[]);groups.get(day).push(ev);}log.innerHTML=[...groups].map(([day,rows])=>'<section class="history-day"><h3>'+esc(day)+'</h3><div>'+rows.map(ev=>'<article class="history-event"><time datetime="'+esc(ev.at)+'">'+esc(new Date(ev.at).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}))+'</time><div><strong>'+esc(ev.action)+'</strong><span>'+esc(ev.detail)+'</span><small>'+esc(ev.actor||'Actor not recorded')+'</small></div></article>').join('')+'</div></section>').join('')||'<p class="history-empty">No recorded actions yet.</p>';$('nativeHistoryCount').textContent=(events?.length||0)+' events · latest 75';}
 function render(){renderQueued=false;if(!api()?.ready||!wb()?.submissionId||wb().restoreError||W.__STM_NATIVE_SESSION_BLOCKED)return;const s=snapshot();$('nativeFormsCount').textContent=s.forms.filter(x=>x.on).length+' of '+s.forms.length+' selected';$('nativeFormsFamily').textContent=s.layer.label||'Choose a layer';$('formsAdd').disabled=!s.layer.key;$('formsReset').disabled=!s.layer.key;
  for(const entry of document.querySelectorAll('#form-subjectivities .subjectivity-entry:not(.other-subjectivity)')){const tag=entry.classList.contains('subjectivity-strong')?'ind':entry.classList.contains('subjectivity-suggested')?'sug':'std',to=document.querySelector('[data-subject-group="'+tag+'"] .native-subjectivity-items');if(entry.parentElement!==to)to.append(entry);}
  decorateCustom();const all=[...s.subjects,...s.custom],on=all.filter(x=>x.on).length;$('nativeSubjectsApplied').textContent=on+' of '+all.length;$('nativeSubjectsCustom').textContent=s.custom.length;$('nativeSubjectsAll').checked=all.length>0&&on===all.length;$('nativeSubjectsAll').indeterminate=on>0&&on<all.length;
  for(const group of document.querySelectorAll('[data-subject-group]')){const key=group.dataset.subjectGroup,rows=key==='custom'?s.custom:s.subjects.filter(x=>x.tag===key);group.querySelector('header span').textContent=rows.filter(x=>x.on).length+' of '+rows.length+' applied';}
  const customOn=s.custom.filter(x=>x.on).length;$('otherSubjectivityCheckbox').checked=s.custom.length>0&&customOn===s.custom.length;$('otherSubjectivityCheckbox').indeterminate=customOn>0&&customOn<s.custom.length;
  const fields={descOps:'description_operations',guidelineConflicts:'guideline_conflicts_text',expLoss:'exposure_to_loss',acctStrengths:'account_strengths'};for(const[id,field]of Object.entries(fields)){const resolved=W.WorkbenchRules?.resolveField(field,W.workbenchActiveSubmission);document.querySelector('[data-narrative-source="'+id+'"]').textContent=resolved?.value==null?'No source text available':$(''+id).dataset.stmExplicitEdit==='1'?'Edited in Workbench':'Source text available';}document.querySelector('[data-narrative-source="pricingRationale"]').textContent='Entered by the underwriter';renderHistory(s.history);
 }
 function schedule(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{try{render();}catch(e){renderQueued=false;notify(e.message);}});}
 $('nativeFormSearch').addEventListener('input',()=>attempt(renderLibrary));$('nativeFormAddSelected').onclick=()=>addForms(false);$('nativeCustomFormAdd').onclick=()=>addForms(true);$('nativeReviewPreviewDownload').onclick=()=>attempt(()=>textDownload(preview.text,preview.name));
 $('nativeSubjectsAll').onchange=e=>action('subj:all',{on:e.target.checked});$('nativeUwReset').onclick=()=>{if(confirm('Restore this underwriting profile and narratives from the submission? Your pricing rationale will be cleared.'))action('uw:reset');};
 $('nativeHistoryExport').onclick=()=>attempt(()=>{const history=snapshot().history;textDownload(history.map(e=>[e.at,e.actor||'Actor not recorded',e.action,e.detail].join('\t')).join('\n')+'\n','workbench-history.txt');});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-review-action],[data-narrative-restore],[data-remove-custom]');if(!b)return;if(b.dataset.narrativeRestore){if(confirm('Restore this narrative from its source?'))action('uw:restore',{key:b.dataset.narrativeRestore});}else if(b.dataset.removeCustom){const wrap=b.closest('.other-input-group'),text=wrap.querySelector('textarea');if(text.value.trim())action('subj:remove',{key:text.dataset.phase7Key});else{wrap.remove();schedule();}}else if(b.dataset.reviewAction==='subjects:reset'){if(confirm('Clear the selected conditions and remove custom conditions?'))action('subj:reset');}else if(b.dataset.reviewAction==='subjects:preview')subjectPreview();});
 document.addEventListener('input',e=>{if(e.target.matches('#form-subjectivities .other-input-group textarea')&&e.isTrusted)attempt(()=>{api().commitNativeSubjects();});if(e.target.closest('#page-underwriting'))schedule();});
 document.addEventListener('change',e=>{if(!e.isTrusted)return;if(e.target.matches('.native-custom-toggle')){const text=e.target.closest('.other-input-group').querySelector('textarea');text.dataset.phase7On=e.target.checked?'1':'0';attempt(()=>api().commitNativeSubjects());}else if(e.target.matches('#otherSubjectivityCheckbox')){for(const t of document.querySelectorAll('#form-subjectivities .other-input-group textarea'))t.dataset.phase7On=e.target.checked?'1':'0';attempt(()=>api().commitNativeSubjects());}else if(e.target.matches('#form-subjectivities .subjectivity-entry input[type=checkbox]'))attempt(()=>api().commitNativeSubjects());schedule();});
 function validate(){for(const id of ['resConstPct','comConstPct']){const e=$(id),v=e.value;if(e.validity.badInput||e.validity.stepMismatch||v!==''&&(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>100)){e.setCustomValidity('Enter a percentage between 0 and 100 with at most two decimal places.');e.reportValidity();throw Error('Construction percentages must be valid numbers between 0 and 100 with at most two decimal places.');}e.setCustomValidity('');}}
 $('nativeFormLibrary').addEventListener('change',e=>{if(e.target.matches('input[type=checkbox]')){if(e.target.checked)picks.add(e.target.value);else picks.delete(e.target.value);$('nativeFormAddSelected').disabled=!picks.size;}});
 $('nativeFormsDialog').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('input:not([type=checkbox])'))e.preventDefault();});
 const before=new Map();document.addEventListener('focusin',e=>{if(e.target.matches('#page-underwriting input:not([readonly]),#page-underwriting textarea,#page-underwriting select'))before.set(e.target,e.target.value);});
 document.addEventListener('focusout',e=>{if(before.has(e.target)){const old=before.get(e.target);before.delete(e.target);if(old!==e.target.value)attempt(()=>api().record(owned(),'Underwriting edited',e.target.id));}});
 document.addEventListener('input',e=>{if(['resConstPct','comConstPct'].includes(e.target.id))e.target.setCustomValidity('');});
 W.__STM_NATIVE_REVIEW={previewForms,downloadForm,openForms,addCustomDraft,resetForms:()=>action('forms:reset'),renderHistory,refresh:schedule,notify,validate};for(const name of ['stm:workbench-loaded','stm:review-updated','stm:worksheets-updated'])W.addEventListener(name,schedule);schedule();
});
