/* Phase 5: presentation adapter for the July workbench.
 * The DOM below remains the original application's calculation/input surface.
 * This adapter adds structural persistence, not a replacement rating engine.
 */
(function(global){
 'use strict';
 const clone=x=>JSON.parse(JSON.stringify(x));
 const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
 const scalarIds=['dealName','polEff','polExp','homeState','admission','clearedFor','businessUnit','subBusinessUnit','layerType','underwriter','assistant','paper','subDate','quoteExp','targetDate','createDate'];
 const lossConfig={gl:{years:'glLossRows',large:'glLargeLossRows',add:'addGlYear',remove:'removeGlYear',addLarge:'addGlLargeLoss',removeLarge:'removeGlLargeLoss',noLoss:'noLossesGlChk'},auto:{years:'autoLossRows',large:'autoLargeLossRows',add:'addAutoYear',remove:'removeAutoYear',addLarge:'addAutoLargeLoss',removeLarge:'removeAutoLargeLoss',noLoss:'noLossesAutoChk'}};
 function controls(root){return root?Array.from(root.querySelectorAll('input,select,textarea')).filter(el=>!el.matches('.flatpickr-alt-input,.stm-date-alt-input')&&el.dataset.stmDateAlt!=='1'&&!(el.previousElementSibling?._flatpickr?.altInput===el)):[];}
 function dateControl(el){return !!el && (el.type==='date'||el.matches('.date,.limit-date,.loss-date-picker,.large-loss-date')||['polEff','polExp','subDate','quoteExp','targetDate','createDate'].includes(el.id));}
 function dateISO(v){v=String(v||'').trim();if(!v)return '';let m=v.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m){let a=v.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2}|\d{4})$/);if(!a)return '';m=['',a[3].length===2?'20'+a[3]:a[3],a[1].padStart(2,'0'),a[2].padStart(2,'0')];}const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]));return d.getFullYear()===+m[1]&&d.getMonth()===+m[2]-1&&d.getDate()===+m[3]?m.slice(1).join('-'):'';}
 global.STMWorkbenchPhase5={install(ctx){
  const {api,edits,applyEl,markDirty,mirror,changed,recordHistory,addCoverageEntry,coverageTypes,initDates,recalc,applyLayer}=ctx;
  const doc=global.document,$=id=>doc.getElementById(id);
  let extension={v:1,loss:{},coverage:null,coverageAll:false,touched:[],views:{},dialogs:{},blanks:[]};
  let mutation=false;
  const initialDefault=new Map();
  function categoryNodes(){return Array.from(doc.querySelectorAll('#risk-limits .limits-category')).map(cat=>{const list=cat.querySelector('.limits-list')||cat;const id=list.id?.replace('-limits-list','')||(cat.dataset.visibility==='lead-only'?'lead':'');return {cat,list,id,name:cat.querySelector('h3,h4')?.textContent.trim()||id};}).filter(x=>x.id);}
  function entries(list){return Array.from(list.querySelectorAll('.limit-entry')).filter(e=>!e.closest('.limit-templates'));}
  function cleanClone(node){const n=node.cloneNode(true);n.querySelectorAll('.flatpickr-alt-input,.stm-date-alt-input,[data-stm-date-alt="1"]').forEach(e=>e.remove());n.querySelectorAll('input').forEach(e=>{if(dateControl(e)){e.type='text';e.classList.remove('flatpickr-input');delete e.dataset.stmDateHiddenCanonical;}});return n;}
  categoryNodes().forEach(g=>entries(g.list).forEach(e=>{const panel=e.querySelector('.limit-details-panel');if(e.classList.contains('default-entry')&&panel)initialDefault.set(panel.id,cleanClone(e));}));
  function assertOwner(sid){if(api.restoreError)throw new Error(api.restoreError);if(!api.submissionId||sid!==api.submissionId||!global.currentUser)throw new Error('This workbench session is no longer active. Reopen the submission.');try{const r=parent.STM_RUNTIME;if(r&&(r.workbenchWindow!==global||r.activeId!==sid))throw new Error('Stale workbench action rejected.');}catch(e){throw e;}}
  function descriptors(elements,prefix){return elements.map((el,i)=>describe(el,prefix+i));}
  function describe(el,key){if(!el)return null;let label=el.closest('label')?.cloneNode(true);label?.querySelectorAll('input,select,textarea,svg,button').forEach(n=>n.remove());return {key,id:el.id||'',label:label?.textContent.replace(/\s+/g,' ').trim()||el.getAttribute('aria-label')||el.placeholder||'',tag:el.tagName.toLowerCase(),value:el.type==='checkbox'?el.checked:dateControl(el)?dateISO(el.value):el.value,raw:el.value,date:dateControl(el),money:el.classList.contains('currency-input'),readonly:!!el.readOnly,disabled:!!el.disabled,type:el.type||'',placeholder:el.placeholder||'',required:!!el.required,maxLength:el.maxLength>0?el.maxLength:null,min:el.getAttribute('min'),max:el.getAttribute('max'),step:el.getAttribute('step'),options:el.options?Array.from(el.options).map(o=>({value:o.value,label:o.textContent,disabled:o.disabled,group:o.parentElement.tagName==='OPTGROUP'?o.parentElement.label:''})):null,policy:!!el.closest('.policy-options-panel'),filled:el.classList.contains('autofilled-from-platform'),warning:el.classList.contains('money-input-rejected')?'Invalid amount was cleared. Use a non-negative amount or K/M/B notation.':el.classList.contains('money-input-coerced')?'Amount was normalized by the original parser.':''};}
  function lossRows(line,kind){const c=lossConfig[line];if(!c)throw new Error('Unknown loss line');return Array.from($(kind==='large'?c.large:c.years).querySelectorAll(kind==='large'?'.large-loss-row':'.loss-row'));}
  function assignRowKeys(line,kind){return lossRows(line,kind).map(row=>{if(!row.dataset.phase5Key)row.dataset.phase5Key='r'+(global.crypto.randomUUID?.()||Array.from(global.crypto.getRandomValues(new Uint32Array(4))).join('-'));return row;});}
  function lossSnapshot(line){const c=lossConfig[line];return {noLoss:$(c.noLoss).checked,years:assignRowKeys(line,'years').map(row=>({key:row.dataset.phase5Key,cells:controls(row).map(api.serializeElement)})),large:assignRowKeys(line,'large').map(row=>({key:row.dataset.phase5Key,cells:controls(row).map(api.serializeElement)}))};}
  function panelId(entry){return entry.querySelector('.limit-details-panel')?.id||'';}
  function applyTitle(entry,title){entry.dataset.phase5Title=title;const el=entry.querySelector('.limit-entry-header .checkbox-label span,.limit-entry-name');if(el)el.textContent=title;}
  function normalizeEntry(entry){const p=entry.querySelector('.limit-details-panel');if(!p)return;controls(p).forEach((el,i)=>{if(!el.readOnly)el.id='stm-coverage-'+p.id+'-'+i;});}
  function coverageSnapshot(){return categoryNodes().map(g=>({id:g.id,items:entries(g.list).map((e,position)=>{const p=e.querySelector('.limit-details-panel');return {position,id:p.id,type:e.dataset.coverageType||'',defaultKey:e.dataset.phase5Default||(initialDefault.has(p.id)?p.id:null),title:e.dataset.phase5Title||null,included:!!e.querySelector('input[data-target]')?.checked,open:p.classList.contains('visible'),policyLayer:e.querySelector('input[data-policy-layer]')?.checked??null,fields:controls(p).map(api.serializeElement)};}).filter(e=>extension.coverageAll||extension.touched.includes(e.type))}));}
  function touchType(type){if(!extension.touched.includes(type))extension.touched.push(type);extension.coverage=coverageSnapshot();}
  function capture(){Object.keys(extension.loss).forEach(l=>extension.loss[l]=lossSnapshot(l));if(extension.coverage)extension.coverage=coverageSnapshot();if(Object.keys(extension.loss).length||extension.coverage||Object.keys(extension.dialogs).length||Object.keys(extension.views).length||extension.blanks.length){const prior=edits.map.__phase5;if(!prior||JSON.stringify(prior.data)!==JSON.stringify(extension))edits.map.__phase5={data:clone(extension),t:Date.now()};}}
  function persist(){capture();changed();mirror();}
  function setElement(el,value){if(!el||el.disabled||el.readOnly)throw new Error('This field is derived or unavailable.');if(el.tagName==='SELECT'&&!Array.from(el.options).some(o=>o.value===String(value)&&!o.disabled))throw new Error('Invalid selection.');if(dateControl(el)&&value&&!dateISO(value))throw new Error('Enter a valid calendar date.');el.dataset.stmExplicitEdit='1';applyEl(el,el.type==='checkbox'?{c:!!value}:{v:dateControl(el)?dateISO(value):String(value??'')},true);el.dataset.stmExplicitEdit='1';if(el.type!=='checkbox'&&el.value===''){const key=el.id||(el.name?'name:'+el.name:null);if(key&&!extension.blanks.includes(key))extension.blanks.push(key);}markDirty(el);return describe(el,el.id);}
  function restoreCells(root,values){const els=controls(root);values.forEach((v,i)=>{const el=els[i];if(!el)return;if(el.tagName==='SELECT'&&own(v,'v')&&!Array.from(el.options).some(o=>o.value===String(v.v))){const opt=doc.createElement('option');opt.value=String(v.v);opt.textContent=String(v.v);el.add(opt);}if(el.readOnly){if(own(v,'v'))el.value=v.v;return;}applyEl(el,v,false);el.dataset.stmExplicitEdit='1';});}
  function restoreLoss(line,saved){const c=lossConfig[line];for(const kind of ['years','large']){const rows=saved[kind];if(!Array.isArray(rows)||rows.length>1000||kind==='years'&&!rows.length)throw new Error('Invalid saved loss rows');let current=lossRows(line,kind);while(current.length>rows.length){current[current.length-1].remove();current.pop();}let count=0;while(current.length<rows.length){$(kind==='years'?c.add:c.addLarge).click();current=lossRows(line,kind);if(++count>rows.length+2)throw new Error('Loss table could not be restored');}rows.forEach((r,i)=>{current[i].dataset.phase5Key=r.key;restoreCells(current[i],r.cells);});if(kind==='large'&&!rows.length){$(c.large).querySelectorAll('.large-loss-header').forEach(n=>n.remove());const prev=$(c.large).previousElementSibling;if(prev?.classList.contains('large-losses-heading'))prev.remove();}}
   $(c.noLoss).checked=!!saved.noLoss;
  }
  function restoreCoverage(saved){if(!Array.isArray(saved))return;for(const g of categoryNodes()){const group=saved.find(x=>x.id===g.id);if(!group)continue;if(!Array.isArray(group.items)||group.items.length>500)throw new Error('Invalid coverage snapshot');entries(g.list).forEach((e,i)=>e.dataset.p5RestoreOrder=i);entries(g.list).filter(e=>extension.coverageAll||extension.touched.includes(e.dataset.coverageType)).forEach(e=>{controls(e).forEach(el=>{try{el._flatpickr?.destroy();}catch(_){}});e.remove();});for(const s of group.items){let e;if(s.defaultKey&&initialDefault.has(s.defaultKey)){e=cleanClone(initialDefault.get(s.defaultKey));g.list.appendChild(e);initDates(e);e.dataset.phase5Default=s.defaultKey;}else{if(!own(coverageTypes[g.id]||{},s.type))throw new Error('Unknown saved coverage type: '+s.type);e=addCoverageEntry(s.type,g.list);}if(!e)throw new Error('Unable to restore coverage');e.dataset.p5RestoreOrder=s.position??999;const p=e.querySelector('.limit-details-panel');p.id=s.id;const cb=e.querySelector('input[data-target]');if(cb){cb.dataset.target=s.id;cb.checked=!!s.included;}const cl=e.querySelector('input[data-policy-layer]');if(cl)cl.checked=!!s.policyLayer;e.querySelector('.policy-options-panel')?.classList.toggle('visible',!!s.policyLayer);p.classList.toggle('visible',!!s.open);e.querySelector('.collapse-arrow')?.classList.toggle('expanded',!!s.open);if(s.title)applyTitle(e,s.title);normalizeEntry(e);restoreCells(p,s.fields||[]);}entries(g.list).sort((a,b)=>Number(a.dataset.p5RestoreOrder)-Number(b.dataset.p5RestoreOrder)).forEach(e=>g.list.appendChild(e));}
   applyLayer();recalc();
  }
  function dialogConfig(which){return which==='insured'?{form:'insuredForm',button:'insuredSaveBtn',copy:'sameAsMailingChk'}:which==='broker'?{form:'brokerForm',button:'brokerSaveBtn'}:null;}
  function commitDialog(which,values,restore=false){const c=dialogConfig(which);if(!c)throw new Error('Unknown dialog');const form=$(c.form);const els=controls(form).filter(e=>e.name||e.id===c.copy);for(const el of els){const key=el.name||el.id;if(!own(values,key))continue;if(el.tagName==='SELECT'&&!Array.from(el.options).some(o=>o.value===String(values[key])))throw new Error('Invalid dialog selection');if(el.type==='checkbox')el.checked=!!values[key];else el.value=String(values[key]??'');}
   if(which==='insured'&&$(c.copy).checked){for(const suffix of ['Street','Suite','City','State','Zip']){const a=form.elements.namedItem('mail'+suffix),b=form.elements.namedItem('risk'+suffix);b.value=a.value;}}
   if(!restore&&!form.checkValidity())throw new Error('Complete the required address or broker fields.');
   // Call the existing commit handler directly, not a hidden dialog's default submit.
   $(c.button).onclick();
   for(const el of els){if(el.type!=='checkbox')el.dataset.stmExplicitEdit='1';if(!restore)markDirty(el);}
   extension.dialogs[which]=Object.fromEntries(els.map(e=>[e.name||e.id,e.type==='checkbox'?e.checked:e.value]));
  }

  function validate(saved){
   if(!saved)return true;
   const s=saved.data;
   const object=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
   const safe=x=>typeof x==='string'&&/^[A-Za-z0-9_-]{1,180}$/.test(x)&&!['__proto__','prototype','constructor'].includes(x);
   const fail=()=>{throw new Error('Saved workbench structure could not be validated. No edits were applied. Keep the recovery data and reopen a valid saved version.');};
   if(!object(s)||s.v!==1||!object(s.loss||{})||!object(s.dialogs||{})||!object(s.views||{})||!Array.isArray(s.touched||[])||!Array.isArray(s.blanks||[]))fail();
   const knownTypes=new Set(Object.values(coverageTypes).flatMap(x=>Object.keys(x)));
   initialDefault.forEach(e=>knownTypes.add(e.dataset.coverageType));
   if((s.touched||[]).some(t=>!knownTypes.has(t))||(s.blanks||[]).some(k=>typeof k!=='string'||k.length>250||!/^([A-Za-z0-9_-]+|name:[A-Za-z0-9_-]+)$/.test(k)))fail();
   const cell=c=>object(c)&&((own(c,'v')&&(typeof c.v==='string'||typeof c.v==='number'))||(own(c,'c')&&typeof c.c==='boolean'));
   const keys=new Set();
   for(const [line,l] of Object.entries(s.loss||{})){
    if(!own(lossConfig,line)||!object(l)||typeof l.noLoss!=='boolean')fail();
    for(const kind of ['years','large']){
     if(!Array.isArray(l[kind])||l[kind].length>1000||(kind==='years'&&!l[kind].length))fail();
     for(const r of l[kind]){if(!object(r)||!safe(r.key)||keys.has(r.key)||!Array.isArray(r.cells)||r.cells.length!==(kind==='years'?7:5)||!r.cells.every(cell))fail();keys.add(r.key);}
    }
   }
   if(s.coverage!==null&&s.coverage!==undefined){
    if(!Array.isArray(s.coverage)||s.coverage.length>4)fail();
    const groups=new Set(),ids=new Set();
    for(const g of s.coverage){
     if(!object(g)||!categoryNodes().some(c=>c.id===g.id)||groups.has(g.id)||!Array.isArray(g.items)||g.items.length>500)fail();groups.add(g.id);
     for(const c of g.items){
      if(!object(c)||!safe(c.id)||ids.has(c.id)||!knownTypes.has(c.type)||typeof c.included!=='boolean'||typeof c.open!=='boolean'||!Array.isArray(c.fields)||c.fields.length>60||!c.fields.every(cell)||(!s.coverageAll&&!(s.touched||[]).includes(c.type)))fail();ids.add(c.id);
      if(c.defaultKey){const d=initialDefault.get(c.defaultKey);if(!d||d.dataset.coverageType!==c.type)fail();}
      else if(!own(coverageTypes[g.id]||{},c.type))fail();
      if(c.title!==null&&c.title!==undefined&&(typeof c.title!=='string'||c.title.length>500))fail();
     }
    }
   }
   for(const [id,v]of Object.entries(s.views||{}))if(!safe(id)||!object(v)||(own(v,'open')&&typeof v.open!=='boolean')||(own(v,'title')&&(typeof v.title!=='string'||v.title.length>500)))fail();
   for(const [which,values]of Object.entries(s.dialogs||{})){
    const cfg=dialogConfig(which);if(!cfg||!object(values))fail();const els=controls($(cfg.form));
    for(const [key,value]of Object.entries(values)){const el=els.find(e=>(e.name||e.id)===key);if(!el||(el.type==='checkbox'?typeof value!=='boolean':typeof value!=='string'))fail();}
   }
   return true;
  }
  function locate(key){if(scalarIds.includes(key))return $(key);const p=key.split('|');if(p[0]==='loss'&&lossConfig[p[1]]&&['years','large'].includes(p[2]))return controls(assignRowKeys(p[1],p[2]).find(r=>r.dataset.phase5Key===p[3]))[+p[4]];if(p[0]==='cov'){const el=$(p[1]);if(!el?.matches('.limit-details-panel')||el.closest('.limit-templates'))return null;return controls(el)[+p[2]];}return null;}
  const bridge={
   ready:true,controls,dateISO,validate,
   ownsLoss(id){return Object.entries(lossConfig).some(([line,c])=>!!extension.loss[line]&&(c.years===id||c.large===id));},
   ownsCoverage(type){return !!extension.coverage&&(extension.coverageAll||extension.touched.includes(type));},
   ownsDialog(field){return field==='mailing_address'||field==='controlling_address'?!!extension.dialogs.insured:!!extension.dialogs.broker;},
   capture,
   restore(saved){if(!saved)return;validate(saved);const s=clone(saved.data);if(s.v!==1)throw new Error('Unsupported workbench structure version');extension={v:1,loss:s.loss||{},coverage:s.coverage||null,coverageAll:!!s.coverageAll,touched:s.touched||[],views:s.views||{},dialogs:s.dialogs||{},blanks:s.blanks||[]};for(const [line,v]of Object.entries(extension.loss)){if(!lossConfig[line])throw new Error('Unknown saved loss line');restoreLoss(line,v);}restoreCoverage(extension.coverage);for(const [id,v] of Object.entries(extension.views)){const p=$(id),e=p?.closest('.limit-entry');if(!e)continue;if(own(v,'open')){p.classList.toggle('visible',v.open);e.querySelector('.collapse-arrow')?.classList.toggle('expanded',v.open);}if(own(v,'title'))applyTitle(e,v.title);}for(const [which,v]of Object.entries(extension.dialogs))commitDialog(which,v,true);for(const key of extension.blanks){let el=key.startsWith('name:')?doc.querySelector('[name="'+CSS.escape(key.slice(5))+'"]'):$(key);if(el){el.dataset.stmExplicitEdit='1';el.dataset.userSet='1';}}capture();},
   read(sid){assertOwner(sid);const fields=Object.fromEntries(scalarIds.map(id=>[id,describe($(id),id)]));const texts={};['dealNum','dealType','dealStatus','mailingTxt','controllingTxt','brokerCoTxt','brokerTypeTxt','brokerAddrTxt','brokerNameTxt','regionTxt','statTermValue','statTermCaption','statQuoteValue','statQuoteCaption','statTargetValue','statTargetCaption','statAssignedValue','statAssignedCaption'].forEach(id=>texts[id]=$(id)?.textContent.trim()||'');const loss={};for(const [line,c]of Object.entries(lossConfig)){loss[line]={noLoss:$(c.noLoss).checked,years:assignRowKeys(line,'years').map(r=>({key:r.dataset.phase5Key,fields:descriptors(controls(r),'loss|'+line+'|years|'+r.dataset.phase5Key+'|')})),large:assignRowKeys(line,'large').map(r=>({key:r.dataset.phase5Key,fields:descriptors(controls(r),'loss|'+line+'|large|'+r.dataset.phase5Key+'|')}))};}
    const coverage=categoryNodes().filter(g=>!g.cat.classList.contains('is-hidden')&&g.cat.style.display!=='none').map(g=>({id:g.id,name:g.name,choices:coverageTypes[g.id]||{},items:entries(g.list).map(e=>{const p=e.querySelector('.limit-details-panel');return {id:p.id,type:e.dataset.coverageType,title:e.dataset.phase5Title||ctx.coverageName(e),included:!!e.querySelector('input[data-target]')?.checked,open:p.classList.contains('visible'),policyLayer:e.querySelector('input[data-policy-layer]')?.checked??null,fields:descriptors(controls(p),'cov|'+p.id+'|')};})}));return {id:sid,revision:api.revision,dirty:api.dirty,fields,texts,loss,coverage};},
   set(sid,key,value){assertOwner(sid);const el=locate(key);if(!el)throw new Error('Field no longer exists. Refresh the page.');const p=key.split('|');if(p[0]==='loss')extension.loss[p[1]]=lossSnapshot(p[1]);if(p[0]==='cov'&&!initialDefault.has(p[1]))touchType(el.closest('.limit-entry').dataset.coverageType);const oldLayer=$('layerType').value;const result=setElement(el,value);if(key==='layerType'&&oldLayer!==el.value){if(oldLayer.split(' ')[0]!==el.value.split(' ')[0]){extension.coverageAll=true;extension.views={};extension.coverage=coverageSnapshot();}recordHistory('Layer type edited',el.value);}persist();return result;},
   action(sid,action,data={}){assertOwner(sid);if(mutation)throw new Error('A workbench action is already in progress');mutation=true;try{if(action.startsWith('loss:')){const c=lossConfig[data.line];if(!c)throw new Error('Unknown loss line');const name=action.slice(5);if(!['noLoss','addYear','removeYear','addLarge','removeLarge'].includes(name))throw new Error('Unknown loss action');if((name==='addYear'||name==='addLarge')&&lossRows(data.line,name==='addYear'?'years':'large').length>=1000)throw new Error('This loss table has reached its supported 1,000-row capacity. Remove a row before adding another.');extension.loss[data.line]=lossSnapshot(data.line);if(name==='noLoss'){const cb=$(c.noLoss);applyEl(cb,{c:!cb.checked},true);markDirty(cb);}else{const button={addYear:c.add,removeYear:c.remove,addLarge:c.addLarge,removeLarge:c.removeLarge}[name];if(!button)throw new Error('Unknown loss action');$(button).click();}recordHistory('Loss history edited',data.line+' '+name);}else if(action.startsWith('coverage:')){const name=action.slice(9);if(name==='add'){const g=categoryNodes().find(g=>g.id===data.group);if(!g||!own(coverageTypes[g.id]||{},data.type))throw new Error('Unknown coverage type');if(entries(g.list).length>=500)throw new Error('This coverage group has reached its supported 500-entry capacity. Remove an entry before adding another.');touchType(data.type);const e=addCoverageEntry(data.type,g.list);normalizeEntry(e);const cb=e.querySelector('input[data-target]');if(cb)applyEl(cb,{c:true},true);}else{const p=$(data.id),e=p?.closest('.limit-entry');if(!e||e.closest('.limit-templates'))throw new Error('Coverage no longer exists');if(!['fold','title'].includes(name))touchType(e.dataset.coverageType);if(name==='delete'){e.remove();recordHistory('Coverage removed',ctx.coverageName(e));}else if(name==='toggle'){const cb=e.querySelector('input[data-target]');if(cb)applyEl(cb,{c:!cb.checked},true);}else if(name==='fold'){p.classList.toggle('visible');extension.views[p.id]={...(extension.views[p.id]||{}),open:p.classList.contains('visible')};e.querySelector('.collapse-arrow')?.classList.toggle('expanded',p.classList.contains('visible'));}else if(name==='carrier'){const cb=e.querySelector('input[data-policy-layer]');if(cb)applyEl(cb,{c:!cb.checked},true);}else if(name==='title'){applyTitle(e,String(data.value||'').trim().slice(0,500)||ctx.coverageName(e));extension.views[p.id]={...(extension.views[p.id]||{}),title:e.dataset.phase5Title};}else throw new Error('Unknown coverage action');}recalc();}else if(action==='dialog:save'){commitDialog(data.which,data.values);}else throw new Error('Unknown workbench action');persist();return true;}finally{mutation=false;}},
   dialog(sid,which){assertOwner(sid);const c=dialogConfig(which);if(!c)throw new Error('Unknown dialog');if(which==='insured'&&!extension.dialogs.insured)ctx.prefillInsured();return controls($(c.form)).filter(e=>e.name||e.id===c.copy).map(e=>({...describe(e,e.name||e.id),key:e.name||e.id}));}
  };
  global.__STM_WB_PHASE5=bridge;
  return bridge;
 }};
})(window);
